[env]
monitor_speed = 115200
framework = arduino
build_flags = 
    -DCORE_DEBUG_LEVEL=0
    -std=c++17

; Environment for ESP32-WROOM-32D (Default receiver with hardware DAC on GPIO 25)
[env:esp32dev]
platform = espressif32
board = esp32dev
build_flags = 
    ${env.build_flags}
    -DBOARD_ESP32_WROOM

; Environment for ESP32-S3 DevKit (High-speed engine / transmitter)
[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
build_flags = 
    ${env.build_flags}
    -DBOARD_ESP32_S3
